# Generated by Django 5.0.3 on 2024-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='artikel/')),
                ('teks', models.TextField()),
            ],
        ),
    ]
