# Generated by Django 5.0.3 on 2024-03-27 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_datablog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablog',
            name='penulis',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
