# Generated by Django 5.0.3 on 2024-03-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_datablog_penulis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datablog',
            name='penulis',
        ),
    ]
