# Generated by Django 5.0.3 on 2024-03-27 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_datablog_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablog',
            name='penulis',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
